### ISSUE TITLE
[doc] Version dependency - Python 3.9

### ISSUE THREAD

**Issue by tsdobbs** [Bioprotocols/container-ontology#20] opened 2022-03-01 17:16 UTC
The file `src/container_api/client_api.py` uses `str.removeprefix()`, which was [implemented in Python 3.9.0](https://www.geeksforgeeks.org/python-string-removeprefix-function/). Not being familiar with `removeprefix()` and running on an old 3.8.10 install, I spent about 20 minutes trying to debug this before figuring it out.

Python 3.9 is still new enough (~18 months old) that I think it's probably reasonable to indicate it as a requirement in the README to help others out in the future.

**Comment by rpgoldman** [comment] 2022-03-01 17:22
I need to get a better test suite set up so that I can test for things like this.

Would it be reasonable to support this only on Python 3.8+ ?

Going back to 3.7 or 3.6 would radically raise the pain level for me.

**Comment by jakebeal** [comment] 2022-03-01 17:51
3.6 is end-of-life, so it can be ignored.

3.7 is generally pretty easy to do backward compatibility with --- the problem is typically typing, and that can be handled by adding `from __future__ import annotations` at the top.

**Comment by tsdobbs** [comment] 2022-03-01 18:01
I think it's okay to require 3.8+ unless someone raises a compelling reason
to go further back. I did learn just now that Ubuntu LTS 20.0 doesn't seem
to officially support 3.9 or 3.10 yet, although they do run. So to me 3.8
is a sensible stopping point.

Tim

**Comment by rpgoldman** [comment] 2022-03-02 17:52
This should also be fixed in the branch for issue #22 : https://github.com/Bioprotocols/container-ontology/tree/iss22

**Closed** 2022-03-04 21:27 UTC
